GET http://localhost:3001/home/?month=3&search=&page_no=1
###



GET http://localhost:3001/home/stats/?month=11
###

GET http://localhost:3001/home/barchart/?month=11
###

GET http://localhost:3001/home/piechart/?month=11
###

GET http://localhost:3001/home/response/?month=11